<?php

/**
 * BasejobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $jobeet_category_affiliates
 * @property Doctrine_Collection $jobeet_jobs
 * 
 * @method integer             getId()                         Returns the current record's "id" value
 * @method string              getName()                       Returns the current record's "name" value
 * @method timestamp           getCreatedAt()                  Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()                  Returns the current record's "updated_at" value
 * @method Doctrine_Collection getJobeetCategoryAffiliates()   Returns the current record's "jobeet_category_affiliates" collection
 * @method Doctrine_Collection getJobeetJobs()                 Returns the current record's "jobeet_jobs" collection
 * @method jobeetCategory      setId()                         Sets the current record's "id" value
 * @method jobeetCategory      setName()                       Sets the current record's "name" value
 * @method jobeetCategory      setCreatedAt()                  Sets the current record's "created_at" value
 * @method jobeetCategory      setUpdatedAt()                  Sets the current record's "updated_at" value
 * @method jobeetCategory      setJobeetCategoryAffiliates()   Sets the current record's "jobeet_category_affiliates" collection
 * @method jobeetCategory      setJobeetJobs()                 Sets the current record's "jobeet_jobs" collection
 * 
 * @package    capacitacion
 * @subpackage model
 * @author     yo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasejobeetCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobeet_category');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));

        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('jobeetCategoryAffiliate as jobeet_category_affiliates', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('jobeetJob as jobeet_jobs', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}