<?php

/**
 * BasejobeetCategoryAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $affiliate_id
 * @property jobeetAffiliate $affiliate
 * @property jobeetCategory $category
 * 
 * @method integer                 getCategoryId()   Returns the current record's "category_id" value
 * @method integer                 getAffiliateId()  Returns the current record's "affiliate_id" value
 * @method jobeetAffiliate         getAffiliate()    Returns the current record's "affiliate" value
 * @method jobeetCategory          getCategory()     Returns the current record's "category" value
 * @method jobeetCategoryAffiliate setCategoryId()   Sets the current record's "category_id" value
 * @method jobeetCategoryAffiliate setAffiliateId()  Sets the current record's "affiliate_id" value
 * @method jobeetCategoryAffiliate setAffiliate()    Sets the current record's "affiliate" value
 * @method jobeetCategoryAffiliate setCategory()     Sets the current record's "category" value
 * 
 * @package    capacitacion
 * @subpackage model
 * @author     yo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasejobeetCategoryAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobeet_category_affiliate');
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('affiliate_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));


        $this->index('jobeet_category_affiliate_idx', array(
             'fields' => 
             array(
              0 => 'affiliate_id',
             ),
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('jobeetAffiliate as affiliate', array(
             'local' => 'affiliate_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('jobeetCategory as category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}