<?php

/**
 * BasejobeetAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $url
 * @property string $email
 * @property string $token
 * @property integer $is_active
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $jobeet_category_affiliates
 * 
 * @method integer             getId()                         Returns the current record's "id" value
 * @method string              getUrl()                        Returns the current record's "url" value
 * @method string              getEmail()                      Returns the current record's "email" value
 * @method string              getToken()                      Returns the current record's "token" value
 * @method integer             getIsActive()                   Returns the current record's "is_active" value
 * @method timestamp           getCreatedAt()                  Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()                  Returns the current record's "updated_at" value
 * @method Doctrine_Collection getJobeetCategoryAffiliates()   Returns the current record's "jobeet_category_affiliates" collection
 * @method jobeetAffiliate     setId()                         Sets the current record's "id" value
 * @method jobeetAffiliate     setUrl()                        Sets the current record's "url" value
 * @method jobeetAffiliate     setEmail()                      Sets the current record's "email" value
 * @method jobeetAffiliate     setToken()                      Sets the current record's "token" value
 * @method jobeetAffiliate     setIsActive()                   Sets the current record's "is_active" value
 * @method jobeetAffiliate     setCreatedAt()                  Sets the current record's "created_at" value
 * @method jobeetAffiliate     setUpdatedAt()                  Sets the current record's "updated_at" value
 * @method jobeetAffiliate     setJobeetCategoryAffiliates()   Sets the current record's "jobeet_category_affiliates" collection
 * 
 * @package    capacitacion
 * @subpackage model
 * @author     yo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasejobeetAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobeet_affiliate');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));

        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('jobeetCategoryAffiliate as jobeet_category_affiliates', array(
             'local' => 'id',
             'foreign' => 'affiliate_id'));
    }
}