<?php

/**
 * jobeetAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class jobeetAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object jobeetAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('jobeetAffiliate');
    }
}