<?php

/**
 * jobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class jobeetJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object jobeetJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('jobeetJob');
    }
}