<?php

/**
 * jobeetCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class jobeetCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object jobeetCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('jobeetCategory');
    }
}