<?php

/**
 * jobeetCategoryAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class jobeetCategoryAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object jobeetCategoryAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('jobeetCategoryAffiliate');
    }
}