# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: job, action: index }

job_new:
  url:   /trabajo/nuevo
  param: { module: job, action: new }
  requirements: { sf_method: get }

job_show:
  url: /trabajo/:id
  class: sfDoctrineRoute
  options: { model: JobeetJob, type: object }
  param: { module: job, action: show }
  requirements: { sf_method: get }

job_edit:
  url: /trabajo/editar/:id
  class: sfDoctrineRoute
  options: { model: JobeetJob, type: object }
  param: { module: job, action: edit }
  requirements: { sf_method: get }

job_update:
  url: /trabajo/actualizar/:id
  class: sfDoctrineRoute
  options: { model: JobeetJob, type: object }
  param: { module: job, action: update }
  requirements: { sf_method: put }

job_create:
  url: /trabajo/crear
  param: { module: job, action: create }
  requirements: { sf_method: post }

job_delete:
  url: /trabajo/borrar/:id
  class: sfDoctrineRoute
  options: { model: JobeetJob, type: object }
  param: { module: job, action: delete }
  requirements: { sf_method: put }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
